FROM quay.io/rhscl/betka:0.7.1

WORKDIR /tmp/betka-bot

RUN pip3 install --user --no-cache-dir -r tests/test-requirements.txt
ENV PATH="${PATH}:${HOME}/.local/bin/"

USER 1000

CMD ["./run-tests.sh"]
